insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('ACT', 	'ACCOUNTANCY', 	1,	1,	80,0 ,24  ,0  ,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('AE', 	'ALT. ENGLISH', 	1,	1,	100,0,30	,1	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('AE', 	'ALT. ENGLISH', 	1,	1,	100,0,30	,1	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('AE', 	'ALT. ENGLISH', 	1,	1,	100,0,30	,1	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('AGT', 	'AGRICULTURE', 	1,	1,	30,0	,9	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('AGT', 	'AGRICULTURE', 	1,	1,	30,0	,9	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('AGT', 	'AGRICULTURE', 	1,	1,	30,0	,9	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('ANT', 	'ANTHROPOLOGY', 	1,	1,	70,0	,21	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('ATT', 	'AUTOMOTIVE', 	1,	1,	30,0	,9	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('ATT', 	'AUTOMOTIVE', 	1,	1,	30,0	,9	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('ATT', 	'AUTOMOTIVE', 	1,	1,	30,0	,9	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('ATV', 	'AUTOMOBILE TECHNOLOGY', 	1,	1,	40,0	,12	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('B', 	'MIL BENGALI', 	1,	1,	100,0,30	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('B', 	'MIL BENGALI', 	1,	1,	100,0,30	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('B', 	'MIL BENGALI', 	1,	1,	100,0,30	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('BIO', 	'BIOLOGY', 	1,	1,	35,0	,21	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('BMS', 	'BUSINESS MATHS&STATISTICS', 	1,	1,	80,0	,24	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('BNV', 	'BANKING', 	1,	1,	40,0	,12	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('BNV', 	'BANKING', 	1,	1,	40,0	,12	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('BNV', 	'BANKING', 	1,	1,	40,0	,12	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('BSE', 	'BUSINESS ECONOMICS', 	1,	1,	80,0	,24	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('BSM', 	'BUSINESS STUDIES & MGMT', 	1,	1,	80,0	,24	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('BT', 	'BIO-TECHNOLOGY', 	1,	1,	70,0	,21	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('BWT', 	'BEAUTY AND WELLNESS', 	1,	1,	30,0	,9	,0	,0);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('CA', 	'COMPUTER APPLICATION', 	1,	1,	70,0	,21	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('CAC', 	'COST ACCOUNTING   ', 	1,	1,	80,0	,24	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('CHE', 	'CHEMISTRY', 	1,	1,	70,0	,21	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('CNT', 	'CONSTRUCTION', 	1,	1,	30,0	,9	,0	,0);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('CSC', 	'COMPUTER SCIENCE  ', 	1,	1,	70,0	,21	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('DAV', 	'DAIRYING', 	1,	1,	40,0	,12	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('E', 	'ENGLISH', 	1,	1,	100,0,30	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('E', 	'ENGLISH', 	1,	1,	100,0,30	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('E', 	'ENGLISH', 	1,	1,	100,0,30	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('ECO', 	'ECONOMICS', 	1,	1,	100,0,30	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('ECO', 	'ECONOMICS', 	1,	1,	100,0,30	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('EDU', 	'EDUCATION', 	1,	1,	70	,0,21	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('EDV', 	'ELECTRICAL DOMESTIC APP', 	1,	1,	40,0	,12	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('EHT', 	'ELECTRONICS & HARDWARE', 	1,	1,	30,0	,9	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('EHT', 	'ELECTRONICS & HARDWARE', 	1,	1,	30,0	,9	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('EHT', 	'ELECTRONICS & HARDWARE', 	1,	1,	30,0	,9	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('ELN', 	'ELECTRONICS', 	1,	1,	70,0	,21	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('ES', 	'ELECTIVE SANSKRIT ', 	1,	1,	100,0,30	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('FMA', 	'FUNDAMENTAL OF MGMT ACCTS', 	1,	1,	80,0	,24	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('FTV', 	'FASHION TECHNOLOGY', 	1,	1,	40,0	,12	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('FTV', 	'FASHION TECHNOLOGY', 	1,	1,	40,0	,12	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('FTV', 	'FASHION TECHNOLOGY', 	1,	1,	40,0	,12	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('GEL', 	'GEOLOGY', 	1,	1,	70,0	,21	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('GEO', 	'GEOGRAPHY', 	1,	1,	70,0	,21	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('GEO', 	'GEOGRAPHY', 	1,	1,	70,0	,21	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('H', 	'MIL HINDI', 	1,	1,	100,0,30	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('H', 	'MIL HINDI', 	1,	1,	100,0,30	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('H', 	'MIL HINDI', 	1,	1,	100,0,30	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('HIS', 	'HISTORY', 	1,	1,	100,0,30	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('HOV', 	'HORTICULTURE', 	1,	1,	40,0	,12	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('HSC', 	'HOME SCIENCE', 	1,	1,	70,0	,21	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('IIT', 	'IT & ITES', 	1,	1,	30,0	,9	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('IIT', 	'IT & ITES', 	1,	1,	30,0	,9	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('IIT', 	'IT & ITES', 	1,	1,	30,0	,9	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('IM', 	'INDIAN MUSIC', 	1,	1,	40,0	,12	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('IT', 	'INFORMATION TECHNOLOGY', 	1,	1,	70,0	,21	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('IT', 	'INFORMATION TECHNOLOGY', 	1,	1,	70,0	,21	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('IT', 	'INFORMATION TECHNOLOGY', 	1,	1,	70,0	,21	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('ITV', 	'INFORMATION TECH (ITV)', 	1,	1,	40,0	,12	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('ITV', 	'INFORMATION TECH (ITV)', 	1,	1,	40,0	,12	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('ITV', 	'INFORMATION TECH (ITV)', 	1,	1,	40,0	,12	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('LOG', 	'LOGIC', 	1,	1,	100,0,30	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('M', 	'MATHS', 	1,	1,	100,0,30	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('M', 	'MATHS', 	1,	1,	100,0,30	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('MSF', 	'MULTI SKILLING (FC)', 	1,	1,	30,0	,9	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('MSF', 	'MULTI SKILLING (FC)', 	1,	1,	30,0	,9	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('MSF', 	'MULTI SKILLING (FC)', 	1,	1,	30,0	,9	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('MSP', 	'MULTI SKILLING (FP)', 	1,	1,	30,0	,9	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('MSP', 	'MULTI SKILLING (FP)', 	1,	1,	30,0	,9	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('MSP', 	'MULTI SKILLING (FP)', 	1,	1,	30,0	,9	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('MTV', 	'MOBILE TECHNOLOGY ', 	1,	1,	40,0	,12	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('O', 	'MIL ODIA', 	1,	1,	100,0,30	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('O', 	'MIL ODIA', 	1,	1,	100,0,30	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('O', 	'MIL ODIA', 	1,	1,	100,0,30	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('OB', 	'OPT. BENGALI', 	1,	1,	100,0,30	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('OH', 	'OPT. HINDI', 	1,	1,	100,0,30	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('OMV', 	'OFFICE MANAGEMENT ', 	1,	1,	40,0	,12	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('OMV', 	'OFFICE MANAGEMENT ', 	1,	1,	40,0	,12	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('OMV', 	'OFFICE MANAGEMENT ', 	1,	1,	40,0	,12	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('OO', 	'OPT. ODIA', 	1,	1,	100,0,30	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('OP', 	'OPT. PERSIAN', 	1,	1,	100,0,30	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('OS', 	'OPT. SANSKRIT', 	1,	1,	100,0,30	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('OT', 	'OPT. TELUGU', 	1,	1,	100,0,30	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('OU', 	'OPT. URDU', 	1,	1,	100,0,30	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('PHV', 	'PARAMEDICAL & HEALTH CARE', 	1,	1,	40,0	,12	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('PHV', 	'PARAMEDICAL & HEALTH CARE', 	1,	1,	40,0	,12	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('PHV', 	'PARAMEDICAL & HEALTH CARE', 	1,	1,	40,0	,12	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('PHY', 	'PHYSICS', 	1,	1,	70,0	,21	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('PLT', 	'PLUMBER', 	1,	1,	30,0	,9	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('PLT', 	'PLUMBER', 	1,	1,	30,0	,9	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('PLT', 	'PLUMBER', 	1,	1,	30,0	,9	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('PM', 	'PERSONNEL MANAGEMENT', 	1,	1,	100,0,30	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('POL', 	'POL. SCIENCE', 	1,	1,	100,0,30	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('PSY', 	'PSYCHOLOGY', 	1,	1,	70,0	,21	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('PTV', 	'PRINTING TECHNOLOGY', 	1,	1,	40,0	,12	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('PTV', 	'PRINTING TECHNOLOGY', 	1,	1,	40,0	,12	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('PTV', 	'PRINTING TECHNOLOGY', 	1,	1,	40,0	,12	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('RTT', 	'RETAIL', 	1,	1,	30,0	,9	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('RTT', 	'RETAIL', 	1,	1,	30,0	,9	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('RTT', 	'RETAIL', 	1,	1,	30,0	,9	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('S', 	'MIL SANSKRIT', 	1,	1,	100,0,30	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('S', 	'MIL SANSKRIT', 	1,	1,	100,0,30	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('S', 	'MIL SANSKRIT', 	1,	1,	100,0,30	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('SOC', 	'SOCIOLOGY', 	1,	1,	100,0,30	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('STA', 	'STATISTICS', 	1,	1,	70,0	,21	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('STA', 	'STATISTICS', 	1,	1,	70,0	,21	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('T', 	'MIL TELUGU', 	1,	1,	100,30,0	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('T', 	'MIL TELUGU', 	1,	1,	100,30,0	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('T', 	'MIL TELUGU', 	1,	1,	100,30,0	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('THT', 	'TOURISM & HOSPITALITY', 	1,	1,	30,0	,9	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('THT', 	'TOURISM & HOSPITALITY', 	1,	1,	30,0	,9	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('THT', 	'TOURISM & HOSPITALITY', 	1,	1,	30,0	,9	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('TTV', 	'TOURISM & TRAVEL MNG', 	1,	1,	40,0	,12	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('TTV', 	'TOURISM & TRAVEL MNG', 	1,	1,	40,0	,12	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('TTV', 	'TOURISM & TRAVEL MNG', 	1,	1,	40,0	,12	,0	,3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('U', 	'MIL URDU', 	1,	1,	100,0,30	,0	,1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('U', 	'MIL URDU', 	1,	1,	100,0,30	,0	,2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('U', 	'MIL URDU', 	1,	1,	100,0,30	,0	,3);