insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('ACT',	'ACCOUNTANCY', 	0,	1,	20,0,		8,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('AGT',	'AGRICULTURE', 	0,	1,	70,0,		28,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('AGT',	'AGRICULTURE', 	0,	1,	70,0,		28,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('AGT',	'AGRICULTURE', 	0,	1,	70,0,		28,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('ANT',	'ANTHROPOLOGY', 	0,	1,0,	30,		12,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('ATT',	'AUTOMOTIVE', 	0,	1,	70,0,		28,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('ATT',	'AUTOMOTIVE', 	0,	1,	70,0,		28,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('ATT',	'AUTOMOTIVE', 	0,	1,	70,0,		28,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('ATV',	'AUTOMOBILE TECHNOLOGY', 	0,	1,	60,0,		24,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('BIO',	'BIOLOGY', 	0,	1,	15,0,		12,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('BMS',	'BUSINESS MATHS&STATISTICS', 	0,	1,	20,0,		8,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('BNV',	'BANKING', 	0,	1,	60,0,		24,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('BNV',	'BANKING', 	0,	1,	60,0,		24,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('BNV',	'BANKING', 	0,	1,	60,0,		24,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('BSE',	'BUSINESS ECONOMICS', 	0,	1,	20,	0,	8,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('BSM',	'BUSINESS STUDIES & MGMT', 	0,	1,	20,	0,	8,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('BT',	'BIO-TECHNOLOGY', 	0,	1,	30,	0,	12,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('BWT',	'BEAUTY AND WELLNESS', 	0,	1,	70,0,		28,	0,0);	 
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('CA',	'COMPUTER APPLICATION', 	0,	1,	30,0,		12,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('CAC',	'COST ACCOUNTING ', 	0,	1,	20,0,		8,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('CHE',	'CHEMISTRY', 	0,	1,	30,	0,	12,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('CNT',	'CONSTRUCTION', 	0,	1,	70,0,		28,	0,0);	 
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('CSC',	'COMPUTER SCIENCE', 	0,	1,	30,0,		12,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('DAV',	'DAIRYING', 	0,	1,	60,0,		24,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('EDU',	'EDUCATION', 	0,	1,	30,0,		12,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('EDV',	'ELECTRICAL DOMESTIC APP', 	0,	1,	60,0,		24,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('EHT',	'ELECTRONICS & HARDWARE', 	0,	1,	70,0,		28,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('EHT',	'ELECTRONICS & HARDWARE', 	0,	1,	70,0,		28,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('EHT',	'ELECTRONICS & HARDWARE', 	0,	1,	70,0,		28,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('ELN',	'ELECTRONICS', 	0,	1,	30,0,		12,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('FMA',	'FUNDAMENTAL OF MGMT ACCTS', 	0,	1,	20,0,		8,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('FTV',	'FASHION TECHNOLOGY', 	0,	1,	60,0,		24,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('FTV',	'FASHION TECHNOLOGY', 	0,	1,	60,0,		24,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('FTV',	'FASHION TECHNOLOGY', 	0,	1,	60,0,		24,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('GEL',	'GEOLOGY', 	0,	1,	30,	0,	12,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('GEO',	'GEOGRAPHY', 	0,	1,	30,	0,	12,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('GEO',	'GEOGRAPHY', 	0,	1,	30,	0,	12,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('HOV',	'HORTICULTURE', 	0,	1,	60,0,		24,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('HSC',	'HOME SCIENCE', 	0,	1,	30,0,		12,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('IIT',	'IT & ITES', 	0,	1,	70,0,		28,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('IIT',	'IT & ITES', 	0,	1,	70,0,		28,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('IIT',	'IT & ITES', 	0,	1,	70,0,		28,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('IM',	'INDIAN MUSIC', 	0,	1,	60,0,		24,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('IT',	'INFORMATION TECHNOLOGY', 	0,	1,	30,	0,	12,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('IT',	'INFORMATION TECHNOLOGY', 	0,	1,	30,	0,	12,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('IT',	'INFORMATION TECHNOLOGY', 	0,	1,	30,	0,	12,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('ITV',	'INFORMATION TECH (ITV);', 	0,	1,	60,0,		24,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('ITV',	'INFORMATION TECH (ITV);', 	0,	1,	60,0,		24,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('ITV',	'INFORMATION TECH (ITV);', 	0,	1,	60,0,		24,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('MSF',	'MULTI SKILLING (FC);', 	0,	1,	70,0,		28,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('MSF',	'MULTI SKILLING (FC);', 	0,	1,	70,0,		28,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('MSF',	'MULTI SKILLING (FC);', 	0,	1,	70,0,		28,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('MSP',	'MULTI SKILLING (FP);', 	0,	1,	70,0,		28,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('MSP',	'MULTI SKILLING (FP);', 	0,	1,	70,0,		28,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('MSP',	'MULTI SKILLING (FP);', 	0,	1,	70,0,		28,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('MTV',	'MOBILE TECHNOLOGY', 	0,	1,	60,	0,	24,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('OMV',	'OFFICE MANAGEMENT', 	0,	1,	60,	0,	24,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('OMV',	'OFFICE MANAGEMENT', 	0,	1,	60,	0,	24,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('OMV',	'OFFICE MANAGEMENT', 	0,	1,	60,	0,	24,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('PHV',	'PARAMEDICAL & HEALTH CARE', 	0,	1,	60,	0,	24,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('PHV',	'PARAMEDICAL & HEALTH CARE', 	0,	1,	60,	0,	24,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('PHV',	'PARAMEDICAL & HEALTH CARE', 	0,	1,	60,	0,	24,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('PHY',	'PHYSICS', 	0,	1,	30,0,		12,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('PLT',	'PLUMBER', 	0,	1,	70,0,		28,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('PLT',	'PLUMBER', 	0,	1,	70,0,		28,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('PLT',	'PLUMBER', 	0,	1,	70,0,		28,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('PSY',	'PSYCHOLOGY', 	0,	1,	30,0,		12,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('PTV',	'PRINTING TECHNOLOGY', 	0,	1,	60,0,		24,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('PTV',	'PRINTING TECHNOLOGY', 	0,	1,	60,0,		24,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('PTV',	'PRINTING TECHNOLOGY', 	0,	1,	60,0,		24,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('RTT',	'RETAIL', 	0,	1,	70,	0,	28,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('RTT',	'RETAIL', 	0,	1,	70,	0,	28,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('RTT',	'RETAIL', 	0,	1,	70,	0,	28,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('STA',	'STATISTICS', 	0,	1,	30,0,		12,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('STA',	'STATISTICS', 	0,	1,	30,0,		12,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('THT',	'TOURISM & HOSPITALITY', 	0,	1,	70,0,	28,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('THT',	'TOURISM & HOSPITALITY', 	0,	1,	70,0,	28,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('THT',	'TOURISM & HOSPITALITY', 	0,	1,	70,0,	28,	0,	3);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('TTV',	'TOURISM & TRAVEL MNG', 	0,	1,	60,0,	24,	0,	1);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('TTV',	'TOURISM & TRAVEL MNG', 	0,	1,	60,0,	24,	0,	2);
insert into schoolproject.subjects (code,description,is_theroy,paper_no,max_marks,min_marks,pass_marks,is_optional,stream) values('TTV',	'TOURISM & TRAVEL MNG', 	0,	1,	60,0,	24,	0,	3);